import { Router } from "express";
import healthRoute from "./health.route";
import authRoute from "../modules/auth/auth.route";
import userRoute from "../modules/users/user.route";
import tagRoute from "../modules/tags/tag.route";
import systemConfigRoute from "../modules/system-configs/system-config.route";
import speakingRoute from "../modules/speaking/speaking.route";
import listeningRoute from "../modules/listening/listening.route";
import readingRoute from "../modules/reading/reading.route";
import writingRoute from "../modules/writing/writing.route";
import testRoute from "../modules/test/test.route";
import attemptRoute from "../modules/attempts/attempt.route";
import uploadRoute from "../modules/uploads/upload.route";
import teacherReviewRoute from "../modules/teacher-reviews/teacher-review.route";
import commentRoute from "../modules/comments/comment.route";
import blogRoute from "../modules/blogs/blog.route";
import notificationRoute from "../modules/notifications/notification.route";
import reportRoute from "../modules/reports/report.route";
import importRoute from "../modules/imports/import.route";
const router = Router();

router.use("/health", healthRoute);
router.use("/auth", authRoute);
router.use("/users", userRoute);
router.use(tagRoute);
router.use(systemConfigRoute);
router.use(speakingRoute);
router.use(listeningRoute);
router.use(readingRoute);
router.use(writingRoute);
router.use(testRoute);
router.use(attemptRoute);
router.use(uploadRoute);
router.use(teacherReviewRoute);
router.use(commentRoute);
router.use(blogRoute);
router.use(notificationRoute);
router.use(reportRoute);
router.use(importRoute);
export default router;
